/*
 * Web of Science Lookup API
 * Web of Science Lookup is a backend API that maps Web of Science API Subscription (Developer Portal), Clarivate SFDC data, and Caesar Data. The API is used to synchronize data and retrieve customer subscriptions. 
 *
 * The version of the OpenAPI document: 0.1.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.clarivate.wos.lookup_client.model;

import com.clarivate.wos.lookup_client.model.CaesarIdSetReferenceIdentifierList;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CaesarIdSetReferenceIdentifierSet
 */
public class CaesarIdSetReferenceIdentifierSetTest {
    private final CaesarIdSetReferenceIdentifierSet model = new CaesarIdSetReferenceIdentifierSet();

    /**
     * Model tests for CaesarIdSetReferenceIdentifierSet
     */
    @Test
    public void testCaesarIdSetReferenceIdentifierSet() {
        // TODO: test CaesarIdSetReferenceIdentifierSet
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'shipTo'
     */
    @Test
    public void shipToTest() {
        // TODO: test shipTo
    }

    /**
     * Test the property 'soldTo'
     */
    @Test
    public void soldToTest() {
        // TODO: test soldTo
    }

    /**
     * Test the property 'identifierList'
     */
    @Test
    public void identifierListTest() {
        // TODO: test identifierList
    }

    /**
     * Test the property 'customApps'
     */
    @Test
    public void customAppsTest() {
        // TODO: test customApps
    }

    /**
     * Test the property 'entitlementSet'
     */
    @Test
    public void entitlementSetTest() {
        // TODO: test entitlementSet
    }

}
