/*
 * Web of Science Lookup API
 * Web of Science Lookup is a backend API that maps Web of Science API Subscription (Developer Portal), Clarivate SFDC data, and Caesar Data. The API is used to synchronize data and retrieve customer subscriptions. 
 *
 * The version of the OpenAPI document: 0.1.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.clarivate.wos.lookup_client.model;

import com.clarivate.wos.lookup_client.model.CaesarIdSetReferenceIdentifierSet;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CaesarIdSetReference
 */
public class CaesarIdSetReferenceTest {
    private final CaesarIdSetReference model = new CaesarIdSetReference();

    /**
     * Model tests for CaesarIdSetReference
     */
    @Test
    public void testCaesarIdSetReference() {
        // TODO: test CaesarIdSetReference
    }

    /**
     * Test the property 'accountName'
     */
    @Test
    public void accountNameTest() {
        // TODO: test accountName
    }

    /**
     * Test the property 'customerId'
     */
    @Test
    public void customerIdTest() {
        // TODO: test customerId
    }

    /**
     * Test the property 'shipTo'
     */
    @Test
    public void shipToTest() {
        // TODO: test shipTo
    }

    /**
     * Test the property 'soldTo'
     */
    @Test
    public void soldToTest() {
        // TODO: test soldTo
    }

    /**
     * Test the property 'trialStart'
     */
    @Test
    public void trialStartTest() {
        // TODO: test trialStart
    }

    /**
     * Test the property 'trialEnd'
     */
    @Test
    public void trialEndTest() {
        // TODO: test trialEnd
    }

    /**
     * Test the property 'identifierSet'
     */
    @Test
    public void identifierSetTest() {
        // TODO: test identifierSet
    }

}
