/*
 * Web of Science Lookup API
 * Web of Science Lookup is a backend API that maps Web of Science API Subscription (Developer Portal), Clarivate SFDC data, and Caesar Data. The API is used to synchronize data and retrieve customer subscriptions. 
 *
 * The version of the OpenAPI document: 0.1.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.clarivate.wos.lookup_client.model;

import com.clarivate.wos.lookup_client.model.Subscription;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for OpportunityAPIItem
 */
public class OpportunityAPIItemTest {
    private final OpportunityAPIItem model = new OpportunityAPIItem();

    /**
     * Model tests for OpportunityAPIItem
     */
    @Test
    public void testOpportunityAPIItem() {
        // TODO: test OpportunityAPIItem
    }

    /**
     * Test the property 'sfdcProductCode'
     */
    @Test
    public void sfdcProductCodeTest() {
        // TODO: test sfdcProductCode
    }

    /**
     * Test the property 'sfdcProductName'
     */
    @Test
    public void sfdcProductNameTest() {
        // TODO: test sfdcProductName
    }

    /**
     * Test the property 'primaryQuote'
     */
    @Test
    public void primaryQuoteTest() {
        // TODO: test primaryQuote
    }

    /**
     * Test the property 'quoteLines'
     */
    @Test
    public void quoteLinesTest() {
        // TODO: test quoteLines
    }

    /**
     * Test the property 'devPortalSubscriptionItem'
     */
    @Test
    public void devPortalSubscriptionItemTest() {
        // TODO: test devPortalSubscriptionItem
    }

}
