/*
 * Web of Science Lookup API
 * Web of Science Lookup is a backend API that maps Web of Science API Subscription (Developer Portal), Clarivate SFDC data, and Caesar Data. The API is used to synchronize data and retrieve customer subscriptions. 
 *
 * The version of the OpenAPI document: 0.1.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.clarivate.wos.lookup_client.model;

import com.clarivate.wos.lookup_client.model.CaesarIdSetReference;
import com.clarivate.wos.lookup_client.model.InternalUserReference;
import com.clarivate.wos.lookup_client.model.SFDCOpportunityReference;
import com.clarivate.wos.lookup_client.model.Subscription;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SFDCAccount
 */
public class SFDCAccountTest {
    private final SFDCAccount model = new SFDCAccount();

    /**
     * Model tests for SFDCAccount
     */
    @Test
    public void testSFDCAccount() {
        // TODO: test SFDCAccount
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'enterpriseId'
     */
    @Test
    public void enterpriseIdTest() {
        // TODO: test enterpriseId
    }

    /**
     * Test the property 'emailDomain'
     */
    @Test
    public void emailDomainTest() {
        // TODO: test emailDomain
    }

    /**
     * Test the property 'accountOwner'
     */
    @Test
    public void accountOwnerTest() {
        // TODO: test accountOwner
    }

    /**
     * Test the property 'sfdcOpportunities'
     */
    @Test
    public void sfdcOpportunitiesTest() {
        // TODO: test sfdcOpportunities
    }

    /**
     * Test the property 'caesarReference'
     */
    @Test
    public void caesarReferenceTest() {
        // TODO: test caesarReference
    }

    /**
     * Test the property 'portalInfo'
     */
    @Test
    public void portalInfoTest() {
        // TODO: test portalInfo
    }

}
