/*
 * Web of Science Lookup API
 * Web of Science Lookup is a backend API that maps Web of Science API Subscription (Developer Portal), Clarivate SFDC data, and Caesar Data. The API is used to synchronize data and retrieve customer subscriptions. 
 *
 * The version of the OpenAPI document: 0.1.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.clarivate.wos.lookup_client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SFDCOpportunityReference
 */
public class SFDCOpportunityReferenceTest {
    private final SFDCOpportunityReference model = new SFDCOpportunityReference();

    /**
     * Model tests for SFDCOpportunityReference
     */
    @Test
    public void testSFDCOpportunityReference() {
        // TODO: test SFDCOpportunityReference
    }

    /**
     * Test the property 'opportunityIDNumber'
     */
    @Test
    public void opportunityIDNumberTest() {
        // TODO: test opportunityIDNumber
    }

    /**
     * Test the property 'opportunityName'
     */
    @Test
    public void opportunityNameTest() {
        // TODO: test opportunityName
    }

    /**
     * Test the property 'ref'
     */
    @Test
    public void refTest() {
        // TODO: test ref
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'contractExpireDate'
     */
    @Test
    public void contractExpireDateTest() {
        // TODO: test contractExpireDate
    }

    /**
     * Test the property 'stage'
     */
    @Test
    public void stageTest() {
        // TODO: test stage
    }

}
