/*
 * Web of Science Lookup API
 * Web of Science Lookup is a backend API that maps Web of Science API Subscription (Developer Portal), Clarivate SFDC data, and Caesar Data. The API is used to synchronize data and retrieve customer subscriptions. 
 *
 * The version of the OpenAPI document: 0.1.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.clarivate.wos.lookup_client.model;

import com.clarivate.wos.lookup_client.model.OpportunityAPIItem;
import com.clarivate.wos.lookup_client.model.SFDCOpportunityOpportunityOwner;
import com.clarivate.wos.lookup_client.model.SFDCOpportunitySfdcAccount;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SFDCOpportunity
 */
public class SFDCOpportunityTest {
    private final SFDCOpportunity model = new SFDCOpportunity();

    /**
     * Model tests for SFDCOpportunity
     */
    @Test
    public void testSFDCOpportunity() {
        // TODO: test SFDCOpportunity
    }

    /**
     * Test the property 'opportunityIDNumber'
     */
    @Test
    public void opportunityIDNumberTest() {
        // TODO: test opportunityIDNumber
    }

    /**
     * Test the property 'opportunityName'
     */
    @Test
    public void opportunityNameTest() {
        // TODO: test opportunityName
    }

    /**
     * Test the property 'opportunityID'
     */
    @Test
    public void opportunityIDTest() {
        // TODO: test opportunityID
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'contractExpireDate'
     */
    @Test
    public void contractExpireDateTest() {
        // TODO: test contractExpireDate
    }

    /**
     * Test the property 'contractEffectiveDate'
     */
    @Test
    public void contractEffectiveDateTest() {
        // TODO: test contractEffectiveDate
    }

    /**
     * Test the property 'closeDate'
     */
    @Test
    public void closeDateTest() {
        // TODO: test closeDate
    }

    /**
     * Test the property 'createdDate'
     */
    @Test
    public void createdDateTest() {
        // TODO: test createdDate
    }

    /**
     * Test the property 'stage'
     */
    @Test
    public void stageTest() {
        // TODO: test stage
    }

    /**
     * Test the property 'sfdcAccount'
     */
    @Test
    public void sfdcAccountTest() {
        // TODO: test sfdcAccount
    }

    /**
     * Test the property 'opportunityOwner'
     */
    @Test
    public void opportunityOwnerTest() {
        // TODO: test opportunityOwner
    }

    /**
     * Test the property 'emailDomain'
     */
    @Test
    public void emailDomainTest() {
        // TODO: test emailDomain
    }

    /**
     * Test the property 'products'
     */
    @Test
    public void productsTest() {
        // TODO: test products
    }

}
