/*
 * Web of Science Lookup API
 * Web of Science Lookup is a backend API that maps Web of Science API Subscription (Developer Portal), Clarivate SFDC data, and Caesar Data. The API is used to synchronize data and retrieve customer subscriptions. 
 *
 * The version of the OpenAPI document: 0.1.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.clarivate.wos.lookup_client.model;

import com.clarivate.wos.lookup_client.model.SFDCAccountReference;
import com.clarivate.wos.lookup_client.model.SearchMatch;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SFDCAccountListRecord
 */
public class SFDCAccountListRecordTest {
    private final SFDCAccountListRecord model = new SFDCAccountListRecord();

    /**
     * Model tests for SFDCAccountListRecord
     */
    @Test
    public void testSFDCAccountListRecord() {
        // TODO: test SFDCAccountListRecord
    }

    /**
     * Test the property 'accountRef'
     */
    @Test
    public void accountRefTest() {
        // TODO: test accountRef
    }

    /**
     * Test the property 'matches'
     */
    @Test
    public void matchesTest() {
        // TODO: test matches
    }

}
