/*
 * Web of Science Lookup API
 * Web of Science Lookup is a backend API that maps Web of Science API Subscription (Developer Portal), Clarivate SFDC data, and Caesar Data. The API is used to synchronize data and retrieve customer subscriptions. 
 *
 * The version of the OpenAPI document: 0.1.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.clarivate.wos.lookup_client.model;

import java.util.Objects;
import java.util.Arrays;
import com.clarivate.wos.lookup_client.model.CaesarIdSetReferenceIdentifierSet;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Caesar reference that is used when searching other entitites
 */
@ApiModel(description = "Caesar reference that is used when searching other entitites")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-13T01:26:33.372+01:00[Europe/Paris]")
public class CaesarIdSetReference {
  public static final String SERIALIZED_NAME_ACCOUNT_NAME = "accountName";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_NAME)
  private String accountName;

  public static final String SERIALIZED_NAME_CUSTOMER_ID = "customerId";
  @SerializedName(SERIALIZED_NAME_CUSTOMER_ID)
  private String customerId;

  public static final String SERIALIZED_NAME_SHIP_TO = "shipTo";
  @SerializedName(SERIALIZED_NAME_SHIP_TO)
  private String shipTo;

  public static final String SERIALIZED_NAME_SOLD_TO = "soldTo";
  @SerializedName(SERIALIZED_NAME_SOLD_TO)
  private String soldTo;

  public static final String SERIALIZED_NAME_TRIAL_START = "trialStart";
  @SerializedName(SERIALIZED_NAME_TRIAL_START)
  private String trialStart;

  public static final String SERIALIZED_NAME_TRIAL_END = "trialEnd";
  @SerializedName(SERIALIZED_NAME_TRIAL_END)
  private String trialEnd;

  public static final String SERIALIZED_NAME_IDENTIFIER_SET = "identifierSet";
  @SerializedName(SERIALIZED_NAME_IDENTIFIER_SET)
  private List<CaesarIdSetReferenceIdentifierSet> identifierSet = null;


  public CaesarIdSetReference accountName(String accountName) {
    
    this.accountName = accountName;
    return this;
  }

   /**
   * Get accountName
   * @return accountName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAccountName() {
    return accountName;
  }


  public void setAccountName(String accountName) {
    this.accountName = accountName;
  }


  public CaesarIdSetReference customerId(String customerId) {
    
    this.customerId = customerId;
    return this;
  }

   /**
   * Get customerId
   * @return customerId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCustomerId() {
    return customerId;
  }


  public void setCustomerId(String customerId) {
    this.customerId = customerId;
  }


  public CaesarIdSetReference shipTo(String shipTo) {
    
    this.shipTo = shipTo;
    return this;
  }

   /**
   * Get shipTo
   * @return shipTo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getShipTo() {
    return shipTo;
  }


  public void setShipTo(String shipTo) {
    this.shipTo = shipTo;
  }


  public CaesarIdSetReference soldTo(String soldTo) {
    
    this.soldTo = soldTo;
    return this;
  }

   /**
   * Get soldTo
   * @return soldTo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSoldTo() {
    return soldTo;
  }


  public void setSoldTo(String soldTo) {
    this.soldTo = soldTo;
  }


  public CaesarIdSetReference trialStart(String trialStart) {
    
    this.trialStart = trialStart;
    return this;
  }

   /**
   * Get trialStart
   * @return trialStart
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTrialStart() {
    return trialStart;
  }


  public void setTrialStart(String trialStart) {
    this.trialStart = trialStart;
  }


  public CaesarIdSetReference trialEnd(String trialEnd) {
    
    this.trialEnd = trialEnd;
    return this;
  }

   /**
   * Get trialEnd
   * @return trialEnd
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTrialEnd() {
    return trialEnd;
  }


  public void setTrialEnd(String trialEnd) {
    this.trialEnd = trialEnd;
  }


  public CaesarIdSetReference identifierSet(List<CaesarIdSetReferenceIdentifierSet> identifierSet) {
    
    this.identifierSet = identifierSet;
    return this;
  }

  public CaesarIdSetReference addIdentifierSetItem(CaesarIdSetReferenceIdentifierSet identifierSetItem) {
    if (this.identifierSet == null) {
      this.identifierSet = new ArrayList<CaesarIdSetReferenceIdentifierSet>();
    }
    this.identifierSet.add(identifierSetItem);
    return this;
  }

   /**
   * Get identifierSet
   * @return identifierSet
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<CaesarIdSetReferenceIdentifierSet> getIdentifierSet() {
    return identifierSet;
  }


  public void setIdentifierSet(List<CaesarIdSetReferenceIdentifierSet> identifierSet) {
    this.identifierSet = identifierSet;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CaesarIdSetReference caesarIdSetReference = (CaesarIdSetReference) o;
    return Objects.equals(this.accountName, caesarIdSetReference.accountName) &&
        Objects.equals(this.customerId, caesarIdSetReference.customerId) &&
        Objects.equals(this.shipTo, caesarIdSetReference.shipTo) &&
        Objects.equals(this.soldTo, caesarIdSetReference.soldTo) &&
        Objects.equals(this.trialStart, caesarIdSetReference.trialStart) &&
        Objects.equals(this.trialEnd, caesarIdSetReference.trialEnd) &&
        Objects.equals(this.identifierSet, caesarIdSetReference.identifierSet);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountName, customerId, shipTo, soldTo, trialStart, trialEnd, identifierSet);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CaesarIdSetReference {\n");
    sb.append("    accountName: ").append(toIndentedString(accountName)).append("\n");
    sb.append("    customerId: ").append(toIndentedString(customerId)).append("\n");
    sb.append("    shipTo: ").append(toIndentedString(shipTo)).append("\n");
    sb.append("    soldTo: ").append(toIndentedString(soldTo)).append("\n");
    sb.append("    trialStart: ").append(toIndentedString(trialStart)).append("\n");
    sb.append("    trialEnd: ").append(toIndentedString(trialEnd)).append("\n");
    sb.append("    identifierSet: ").append(toIndentedString(identifierSet)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

