/*
 * Web of Science Lookup API
 * Web of Science Lookup is a backend API that maps Web of Science API Subscription (Developer Portal), Clarivate SFDC data, and Caesar Data. The API is used to synchronize data and retrieve customer subscriptions. 
 *
 * The version of the OpenAPI document: 0.1.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.clarivate.wos.lookup_client.model;

import java.util.Objects;
import java.util.Arrays;
import com.clarivate.wos.lookup_client.model.CaesarIdSetReferenceIdentifierList;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * CaesarIdSetReferenceIdentifierSet
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-13T01:26:33.372+01:00[Europe/Paris]")
public class CaesarIdSetReferenceIdentifierSet {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_SHIP_TO = "shipTo";
  @SerializedName(SERIALIZED_NAME_SHIP_TO)
  private String shipTo;

  public static final String SERIALIZED_NAME_SOLD_TO = "soldTo";
  @SerializedName(SERIALIZED_NAME_SOLD_TO)
  private String soldTo;

  public static final String SERIALIZED_NAME_IDENTIFIER_LIST = "identifierList";
  @SerializedName(SERIALIZED_NAME_IDENTIFIER_LIST)
  private List<CaesarIdSetReferenceIdentifierList> identifierList = new ArrayList<CaesarIdSetReferenceIdentifierList>();

  public static final String SERIALIZED_NAME_CUSTOM_APPS = "customApps";
  @SerializedName(SERIALIZED_NAME_CUSTOM_APPS)
  private List<String> customApps = null;

  public static final String SERIALIZED_NAME_ENTITLEMENT_SET = "entitlementSet";
  @SerializedName(SERIALIZED_NAME_ENTITLEMENT_SET)
  private List<String> entitlementSet = new ArrayList<String>();


  public CaesarIdSetReferenceIdentifierSet id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public CaesarIdSetReferenceIdentifierSet name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public CaesarIdSetReferenceIdentifierSet shipTo(String shipTo) {
    
    this.shipTo = shipTo;
    return this;
  }

   /**
   * Get shipTo
   * @return shipTo
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getShipTo() {
    return shipTo;
  }


  public void setShipTo(String shipTo) {
    this.shipTo = shipTo;
  }


  public CaesarIdSetReferenceIdentifierSet soldTo(String soldTo) {
    
    this.soldTo = soldTo;
    return this;
  }

   /**
   * Get soldTo
   * @return soldTo
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getSoldTo() {
    return soldTo;
  }


  public void setSoldTo(String soldTo) {
    this.soldTo = soldTo;
  }


  public CaesarIdSetReferenceIdentifierSet identifierList(List<CaesarIdSetReferenceIdentifierList> identifierList) {
    
    this.identifierList = identifierList;
    return this;
  }

  public CaesarIdSetReferenceIdentifierSet addIdentifierListItem(CaesarIdSetReferenceIdentifierList identifierListItem) {
    this.identifierList.add(identifierListItem);
    return this;
  }

   /**
   * Get identifierList
   * @return identifierList
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public List<CaesarIdSetReferenceIdentifierList> getIdentifierList() {
    return identifierList;
  }


  public void setIdentifierList(List<CaesarIdSetReferenceIdentifierList> identifierList) {
    this.identifierList = identifierList;
  }


  public CaesarIdSetReferenceIdentifierSet customApps(List<String> customApps) {
    
    this.customApps = customApps;
    return this;
  }

  public CaesarIdSetReferenceIdentifierSet addCustomAppsItem(String customAppsItem) {
    if (this.customApps == null) {
      this.customApps = new ArrayList<String>();
    }
    this.customApps.add(customAppsItem);
    return this;
  }

   /**
   * Get customApps
   * @return customApps
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getCustomApps() {
    return customApps;
  }


  public void setCustomApps(List<String> customApps) {
    this.customApps = customApps;
  }


  public CaesarIdSetReferenceIdentifierSet entitlementSet(List<String> entitlementSet) {
    
    this.entitlementSet = entitlementSet;
    return this;
  }

  public CaesarIdSetReferenceIdentifierSet addEntitlementSetItem(String entitlementSetItem) {
    this.entitlementSet.add(entitlementSetItem);
    return this;
  }

   /**
   * Get entitlementSet
   * @return entitlementSet
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public List<String> getEntitlementSet() {
    return entitlementSet;
  }


  public void setEntitlementSet(List<String> entitlementSet) {
    this.entitlementSet = entitlementSet;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CaesarIdSetReferenceIdentifierSet caesarIdSetReferenceIdentifierSet = (CaesarIdSetReferenceIdentifierSet) o;
    return Objects.equals(this.id, caesarIdSetReferenceIdentifierSet.id) &&
        Objects.equals(this.name, caesarIdSetReferenceIdentifierSet.name) &&
        Objects.equals(this.shipTo, caesarIdSetReferenceIdentifierSet.shipTo) &&
        Objects.equals(this.soldTo, caesarIdSetReferenceIdentifierSet.soldTo) &&
        Objects.equals(this.identifierList, caesarIdSetReferenceIdentifierSet.identifierList) &&
        Objects.equals(this.customApps, caesarIdSetReferenceIdentifierSet.customApps) &&
        Objects.equals(this.entitlementSet, caesarIdSetReferenceIdentifierSet.entitlementSet);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, shipTo, soldTo, identifierList, customApps, entitlementSet);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CaesarIdSetReferenceIdentifierSet {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    shipTo: ").append(toIndentedString(shipTo)).append("\n");
    sb.append("    soldTo: ").append(toIndentedString(soldTo)).append("\n");
    sb.append("    identifierList: ").append(toIndentedString(identifierList)).append("\n");
    sb.append("    customApps: ").append(toIndentedString(customApps)).append("\n");
    sb.append("    entitlementSet: ").append(toIndentedString(entitlementSet)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

