/*
 * Web of Science Lookup API
 * Web of Science Lookup is a backend API that maps Web of Science API Subscription (Developer Portal), Clarivate SFDC data, and Caesar Data. The API is used to synchronize data and retrieve customer subscriptions. 
 *
 * The version of the OpenAPI document: 0.1.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.clarivate.wos.lookup_client.model;

import java.util.Objects;
import java.util.Arrays;
import com.clarivate.wos.lookup_client.model.OpportunityAPIItem;
import com.clarivate.wos.lookup_client.model.SFDCOpportunityOpportunityOwner;
import com.clarivate.wos.lookup_client.model.SFDCOpportunitySfdcAccount;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * SFDCOpportunity
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-13T01:26:33.372+01:00[Europe/Paris]")
public class SFDCOpportunity {
  public static final String SERIALIZED_NAME_OPPORTUNITY_I_D_NUMBER = "opportunityIDNumber";
  @SerializedName(SERIALIZED_NAME_OPPORTUNITY_I_D_NUMBER)
  private String opportunityIDNumber;

  public static final String SERIALIZED_NAME_OPPORTUNITY_NAME = "opportunityName";
  @SerializedName(SERIALIZED_NAME_OPPORTUNITY_NAME)
  private String opportunityName;

  public static final String SERIALIZED_NAME_OPPORTUNITY_I_D = "opportunityID";
  @SerializedName(SERIALIZED_NAME_OPPORTUNITY_I_D)
  private String opportunityID;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;

  public static final String SERIALIZED_NAME_CONTRACT_EXPIRE_DATE = "contractExpireDate";
  @SerializedName(SERIALIZED_NAME_CONTRACT_EXPIRE_DATE)
  private String contractExpireDate;

  public static final String SERIALIZED_NAME_CONTRACT_EFFECTIVE_DATE = "contractEffectiveDate";
  @SerializedName(SERIALIZED_NAME_CONTRACT_EFFECTIVE_DATE)
  private String contractEffectiveDate;

  public static final String SERIALIZED_NAME_CLOSE_DATE = "closeDate";
  @SerializedName(SERIALIZED_NAME_CLOSE_DATE)
  private String closeDate;

  public static final String SERIALIZED_NAME_CREATED_DATE = "createdDate";
  @SerializedName(SERIALIZED_NAME_CREATED_DATE)
  private String createdDate;

  public static final String SERIALIZED_NAME_STAGE = "stage";
  @SerializedName(SERIALIZED_NAME_STAGE)
  private String stage;

  public static final String SERIALIZED_NAME_SFDC_ACCOUNT = "sfdcAccount";
  @SerializedName(SERIALIZED_NAME_SFDC_ACCOUNT)
  private SFDCOpportunitySfdcAccount sfdcAccount;

  public static final String SERIALIZED_NAME_OPPORTUNITY_OWNER = "opportunityOwner";
  @SerializedName(SERIALIZED_NAME_OPPORTUNITY_OWNER)
  private SFDCOpportunityOpportunityOwner opportunityOwner;

  public static final String SERIALIZED_NAME_EMAIL_DOMAIN = "emailDomain";
  @SerializedName(SERIALIZED_NAME_EMAIL_DOMAIN)
  private String emailDomain;

  public static final String SERIALIZED_NAME_PRODUCTS = "products";
  @SerializedName(SERIALIZED_NAME_PRODUCTS)
  private List<OpportunityAPIItem> products = null;


  public SFDCOpportunity opportunityIDNumber(String opportunityIDNumber) {
    
    this.opportunityIDNumber = opportunityIDNumber;
    return this;
  }

   /**
   * Opportunity ID Number that is can be used in emails
   * @return opportunityIDNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "OPP-00000000", value = "Opportunity ID Number that is can be used in emails")

  public String getOpportunityIDNumber() {
    return opportunityIDNumber;
  }


  public void setOpportunityIDNumber(String opportunityIDNumber) {
    this.opportunityIDNumber = opportunityIDNumber;
  }


  public SFDCOpportunity opportunityName(String opportunityName) {
    
    this.opportunityName = opportunityName;
    return this;
  }

   /**
   * Opportunity name
   * @return opportunityName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "UNIVERSITE DE POITIERS - Web of Science - 2022", value = "Opportunity name")

  public String getOpportunityName() {
    return opportunityName;
  }


  public void setOpportunityName(String opportunityName) {
    this.opportunityName = opportunityName;
  }


  public SFDCOpportunity opportunityID(String opportunityID) {
    
    this.opportunityID = opportunityID;
    return this;
  }

   /**
   * Get opportunityID
   * @return opportunityID
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getOpportunityID() {
    return opportunityID;
  }


  public void setOpportunityID(String opportunityID) {
    this.opportunityID = opportunityID;
  }


  public SFDCOpportunity type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * Type of opportunity, New, Renewal, Amendment, etc.
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Type of opportunity, New, Renewal, Amendment, etc.")

  public String getType() {
    return type;
  }


  public void setType(String type) {
    this.type = type;
  }


  public SFDCOpportunity contractExpireDate(String contractExpireDate) {
    
    this.contractExpireDate = contractExpireDate;
    return this;
  }

   /**
   * Get contractExpireDate
   * @return contractExpireDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getContractExpireDate() {
    return contractExpireDate;
  }


  public void setContractExpireDate(String contractExpireDate) {
    this.contractExpireDate = contractExpireDate;
  }


  public SFDCOpportunity contractEffectiveDate(String contractEffectiveDate) {
    
    this.contractEffectiveDate = contractEffectiveDate;
    return this;
  }

   /**
   * Get contractEffectiveDate
   * @return contractEffectiveDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getContractEffectiveDate() {
    return contractEffectiveDate;
  }


  public void setContractEffectiveDate(String contractEffectiveDate) {
    this.contractEffectiveDate = contractEffectiveDate;
  }


  public SFDCOpportunity closeDate(String closeDate) {
    
    this.closeDate = closeDate;
    return this;
  }

   /**
   * Get closeDate
   * @return closeDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCloseDate() {
    return closeDate;
  }


  public void setCloseDate(String closeDate) {
    this.closeDate = closeDate;
  }


  public SFDCOpportunity createdDate(String createdDate) {
    
    this.createdDate = createdDate;
    return this;
  }

   /**
   * Get createdDate
   * @return createdDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCreatedDate() {
    return createdDate;
  }


  public void setCreatedDate(String createdDate) {
    this.createdDate = createdDate;
  }


  public SFDCOpportunity stage(String stage) {
    
    this.stage = stage;
    return this;
  }

   /**
   * Get stage
   * @return stage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getStage() {
    return stage;
  }


  public void setStage(String stage) {
    this.stage = stage;
  }


  public SFDCOpportunity sfdcAccount(SFDCOpportunitySfdcAccount sfdcAccount) {
    
    this.sfdcAccount = sfdcAccount;
    return this;
  }

   /**
   * Get sfdcAccount
   * @return sfdcAccount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public SFDCOpportunitySfdcAccount getSfdcAccount() {
    return sfdcAccount;
  }


  public void setSfdcAccount(SFDCOpportunitySfdcAccount sfdcAccount) {
    this.sfdcAccount = sfdcAccount;
  }


  public SFDCOpportunity opportunityOwner(SFDCOpportunityOpportunityOwner opportunityOwner) {
    
    this.opportunityOwner = opportunityOwner;
    return this;
  }

   /**
   * Get opportunityOwner
   * @return opportunityOwner
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public SFDCOpportunityOpportunityOwner getOpportunityOwner() {
    return opportunityOwner;
  }


  public void setOpportunityOwner(SFDCOpportunityOpportunityOwner opportunityOwner) {
    this.opportunityOwner = opportunityOwner;
  }


  public SFDCOpportunity emailDomain(String emailDomain) {
    
    this.emailDomain = emailDomain;
    return this;
  }

   /**
   * Get emailDomain
   * @return emailDomain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getEmailDomain() {
    return emailDomain;
  }


  public void setEmailDomain(String emailDomain) {
    this.emailDomain = emailDomain;
  }


  public SFDCOpportunity products(List<OpportunityAPIItem> products) {
    
    this.products = products;
    return this;
  }

  public SFDCOpportunity addProductsItem(OpportunityAPIItem productsItem) {
    if (this.products == null) {
      this.products = new ArrayList<OpportunityAPIItem>();
    }
    this.products.add(productsItem);
    return this;
  }

   /**
   * Get products
   * @return products
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<OpportunityAPIItem> getProducts() {
    return products;
  }


  public void setProducts(List<OpportunityAPIItem> products) {
    this.products = products;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SFDCOpportunity sfDCOpportunity = (SFDCOpportunity) o;
    return Objects.equals(this.opportunityIDNumber, sfDCOpportunity.opportunityIDNumber) &&
        Objects.equals(this.opportunityName, sfDCOpportunity.opportunityName) &&
        Objects.equals(this.opportunityID, sfDCOpportunity.opportunityID) &&
        Objects.equals(this.type, sfDCOpportunity.type) &&
        Objects.equals(this.contractExpireDate, sfDCOpportunity.contractExpireDate) &&
        Objects.equals(this.contractEffectiveDate, sfDCOpportunity.contractEffectiveDate) &&
        Objects.equals(this.closeDate, sfDCOpportunity.closeDate) &&
        Objects.equals(this.createdDate, sfDCOpportunity.createdDate) &&
        Objects.equals(this.stage, sfDCOpportunity.stage) &&
        Objects.equals(this.sfdcAccount, sfDCOpportunity.sfdcAccount) &&
        Objects.equals(this.opportunityOwner, sfDCOpportunity.opportunityOwner) &&
        Objects.equals(this.emailDomain, sfDCOpportunity.emailDomain) &&
        Objects.equals(this.products, sfDCOpportunity.products);
  }

  @Override
  public int hashCode() {
    return Objects.hash(opportunityIDNumber, opportunityName, opportunityID, type, contractExpireDate, contractEffectiveDate, closeDate, createdDate, stage, sfdcAccount, opportunityOwner, emailDomain, products);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SFDCOpportunity {\n");
    sb.append("    opportunityIDNumber: ").append(toIndentedString(opportunityIDNumber)).append("\n");
    sb.append("    opportunityName: ").append(toIndentedString(opportunityName)).append("\n");
    sb.append("    opportunityID: ").append(toIndentedString(opportunityID)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    contractExpireDate: ").append(toIndentedString(contractExpireDate)).append("\n");
    sb.append("    contractEffectiveDate: ").append(toIndentedString(contractEffectiveDate)).append("\n");
    sb.append("    closeDate: ").append(toIndentedString(closeDate)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    stage: ").append(toIndentedString(stage)).append("\n");
    sb.append("    sfdcAccount: ").append(toIndentedString(sfdcAccount)).append("\n");
    sb.append("    opportunityOwner: ").append(toIndentedString(opportunityOwner)).append("\n");
    sb.append("    emailDomain: ").append(toIndentedString(emailDomain)).append("\n");
    sb.append("    products: ").append(toIndentedString(products)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

