/*
 * Web of Science Lookup API
 * Web of Science Lookup is a backend API that maps Web of Science API Subscription (Developer Portal), Clarivate SFDC data, and Caesar Data. The API is used to synchronize data and retrieve customer subscriptions. 
 *
 * The version of the OpenAPI document: 0.1.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.clarivate.wos.lookup_client.model;

import java.util.Objects;
import java.util.Arrays;
import com.clarivate.wos.lookup_client.model.SFDCOpportunityReference;
import com.clarivate.wos.lookup_client.model.SearchMatch;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * SFDCOpportunityListRecord
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-13T01:26:33.372+01:00[Europe/Paris]")
public class SFDCOpportunityListRecord {
  public static final String SERIALIZED_NAME_OPPORTUNITY_REF = "opportunityRef";
  @SerializedName(SERIALIZED_NAME_OPPORTUNITY_REF)
  private SFDCOpportunityReference opportunityRef;

  public static final String SERIALIZED_NAME_MATCHES = "matches";
  @SerializedName(SERIALIZED_NAME_MATCHES)
  private List<SearchMatch> matches = null;


  public SFDCOpportunityListRecord opportunityRef(SFDCOpportunityReference opportunityRef) {
    
    this.opportunityRef = opportunityRef;
    return this;
  }

   /**
   * Get opportunityRef
   * @return opportunityRef
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public SFDCOpportunityReference getOpportunityRef() {
    return opportunityRef;
  }


  public void setOpportunityRef(SFDCOpportunityReference opportunityRef) {
    this.opportunityRef = opportunityRef;
  }


  public SFDCOpportunityListRecord matches(List<SearchMatch> matches) {
    
    this.matches = matches;
    return this;
  }

  public SFDCOpportunityListRecord addMatchesItem(SearchMatch matchesItem) {
    if (this.matches == null) {
      this.matches = new ArrayList<SearchMatch>();
    }
    this.matches.add(matchesItem);
    return this;
  }

   /**
   * Get matches
   * @return matches
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<SearchMatch> getMatches() {
    return matches;
  }


  public void setMatches(List<SearchMatch> matches) {
    this.matches = matches;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SFDCOpportunityListRecord sfDCOpportunityListRecord = (SFDCOpportunityListRecord) o;
    return Objects.equals(this.opportunityRef, sfDCOpportunityListRecord.opportunityRef) &&
        Objects.equals(this.matches, sfDCOpportunityListRecord.matches);
  }

  @Override
  public int hashCode() {
    return Objects.hash(opportunityRef, matches);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SFDCOpportunityListRecord {\n");
    sb.append("    opportunityRef: ").append(toIndentedString(opportunityRef)).append("\n");
    sb.append("    matches: ").append(toIndentedString(matches)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

