/*
 * Web of Science Lookup API
 * Web of Science Lookup is a backend API that maps Web of Science API Subscription (Developer Portal), Clarivate SFDC data, and Caesar Data. The API is used to synchronize data and retrieve customer subscriptions. 
 *
 * The version of the OpenAPI document: 0.1.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.clarivate.wos.lookup_client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * SFDCOpportunityReference
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-12T17:30:38.696406200+01:00[Europe/Paris]")
public class SFDCOpportunityReference {
  public static final String SERIALIZED_NAME_OPPORTUNITY_I_D_NUMBER = "opportunityIDNumber";
  @SerializedName(SERIALIZED_NAME_OPPORTUNITY_I_D_NUMBER)
  private String opportunityIDNumber;

  public static final String SERIALIZED_NAME_OPPORTUNITY_NAME = "opportunityName";
  @SerializedName(SERIALIZED_NAME_OPPORTUNITY_NAME)
  private String opportunityName;

  public static final String SERIALIZED_NAME_REF = "ref";
  @SerializedName(SERIALIZED_NAME_REF)
  private String ref;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;

  public static final String SERIALIZED_NAME_CONTRACT_EXPIRE_DATE = "contractExpireDate";
  @SerializedName(SERIALIZED_NAME_CONTRACT_EXPIRE_DATE)
  private String contractExpireDate;

  public static final String SERIALIZED_NAME_STAGE = "stage";
  @SerializedName(SERIALIZED_NAME_STAGE)
  private String stage;


  public SFDCOpportunityReference opportunityIDNumber(String opportunityIDNumber) {
    
    this.opportunityIDNumber = opportunityIDNumber;
    return this;
  }

   /**
   * Opportunity ID Number that is can be used in emails
   * @return opportunityIDNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "OPP-00000000", value = "Opportunity ID Number that is can be used in emails")

  public String getOpportunityIDNumber() {
    return opportunityIDNumber;
  }


  public void setOpportunityIDNumber(String opportunityIDNumber) {
    this.opportunityIDNumber = opportunityIDNumber;
  }


  public SFDCOpportunityReference opportunityName(String opportunityName) {
    
    this.opportunityName = opportunityName;
    return this;
  }

   /**
   * Opportunity name
   * @return opportunityName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "UNIVERSITE DE POITIERS - Web of Science - 2022", value = "Opportunity name")

  public String getOpportunityName() {
    return opportunityName;
  }


  public void setOpportunityName(String opportunityName) {
    this.opportunityName = opportunityName;
  }


  public SFDCOpportunityReference ref(String ref) {
    
    this.ref = ref;
    return this;
  }

   /**
   * Link to the full SFDC opportunity data
   * @return ref
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "/SFDCOpportunities/OPP-00000000", value = "Link to the full SFDC opportunity data")

  public String getRef() {
    return ref;
  }


  public void setRef(String ref) {
    this.ref = ref;
  }


  public SFDCOpportunityReference type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * Type of opportunity, New, Renewal, Amendment, etc.
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Type of opportunity, New, Renewal, Amendment, etc.")

  public String getType() {
    return type;
  }


  public void setType(String type) {
    this.type = type;
  }


  public SFDCOpportunityReference contractExpireDate(String contractExpireDate) {
    
    this.contractExpireDate = contractExpireDate;
    return this;
  }

   /**
   * Get contractExpireDate
   * @return contractExpireDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getContractExpireDate() {
    return contractExpireDate;
  }


  public void setContractExpireDate(String contractExpireDate) {
    this.contractExpireDate = contractExpireDate;
  }


  public SFDCOpportunityReference stage(String stage) {
    
    this.stage = stage;
    return this;
  }

   /**
   * Get stage
   * @return stage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getStage() {
    return stage;
  }


  public void setStage(String stage) {
    this.stage = stage;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SFDCOpportunityReference sfDCOpportunityReference = (SFDCOpportunityReference) o;
    return Objects.equals(this.opportunityIDNumber, sfDCOpportunityReference.opportunityIDNumber) &&
        Objects.equals(this.opportunityName, sfDCOpportunityReference.opportunityName) &&
        Objects.equals(this.ref, sfDCOpportunityReference.ref) &&
        Objects.equals(this.type, sfDCOpportunityReference.type) &&
        Objects.equals(this.contractExpireDate, sfDCOpportunityReference.contractExpireDate) &&
        Objects.equals(this.stage, sfDCOpportunityReference.stage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(opportunityIDNumber, opportunityName, ref, type, contractExpireDate, stage);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SFDCOpportunityReference {\n");
    sb.append("    opportunityIDNumber: ").append(toIndentedString(opportunityIDNumber)).append("\n");
    sb.append("    opportunityName: ").append(toIndentedString(opportunityName)).append("\n");
    sb.append("    ref: ").append(toIndentedString(ref)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    contractExpireDate: ").append(toIndentedString(contractExpireDate)).append("\n");
    sb.append("    stage: ").append(toIndentedString(stage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

