/*
 * Web of Science Lookup API
 * Web of Science Lookup is a backend API that maps Web of Science API Subscription (Developer Portal), Clarivate SFDC data, and Caesar Data. The API is used to synchronize data and retrieve customer subscriptions. 
 *
 * The version of the OpenAPI document: 0.1.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.clarivate.wos.lookup_client.model;

import java.util.Objects;
import java.util.Arrays;
import com.clarivate.wos.lookup_client.model.CaesarIdSetReference;
import com.clarivate.wos.lookup_client.model.InternalUserReference;
import com.clarivate.wos.lookup_client.model.SFDCOpportunityReference;
import com.clarivate.wos.lookup_client.model.Subscription;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * SFDCAccount
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-12T17:30:38.696406200+01:00[Europe/Paris]")
public class SFDCAccount {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_ENTERPRISE_ID = "enterpriseId";
  @SerializedName(SERIALIZED_NAME_ENTERPRISE_ID)
  private String enterpriseId;

  public static final String SERIALIZED_NAME_EMAIL_DOMAIN = "emailDomain";
  @SerializedName(SERIALIZED_NAME_EMAIL_DOMAIN)
  private String emailDomain;

  public static final String SERIALIZED_NAME_ACCOUNT_OWNER = "accountOwner";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_OWNER)
  private InternalUserReference accountOwner;

  public static final String SERIALIZED_NAME_SFDC_OPPORTUNITIES = "sfdcOpportunities";
  @SerializedName(SERIALIZED_NAME_SFDC_OPPORTUNITIES)
  private List<SFDCOpportunityReference> sfdcOpportunities = null;

  public static final String SERIALIZED_NAME_CAESAR_REFERENCE = "caesarReference";
  @SerializedName(SERIALIZED_NAME_CAESAR_REFERENCE)
  private CaesarIdSetReference caesarReference;

  public static final String SERIALIZED_NAME_PORTAL_INFO = "portalInfo";
  @SerializedName(SERIALIZED_NAME_PORTAL_INFO)
  private List<Subscription> portalInfo = null;


  public SFDCAccount name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Clarivate", value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public SFDCAccount enterpriseId(String enterpriseId) {
    
    this.enterpriseId = enterpriseId;
    return this;
  }

   /**
   * Get enterpriseId
   * @return enterpriseId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "ACT-00000000", value = "")

  public String getEnterpriseId() {
    return enterpriseId;
  }


  public void setEnterpriseId(String enterpriseId) {
    this.enterpriseId = enterpriseId;
  }


  public SFDCAccount emailDomain(String emailDomain) {
    
    this.emailDomain = emailDomain;
    return this;
  }

   /**
   * Get emailDomain
   * @return emailDomain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "slv.vic.gov.au", value = "")

  public String getEmailDomain() {
    return emailDomain;
  }


  public void setEmailDomain(String emailDomain) {
    this.emailDomain = emailDomain;
  }


  public SFDCAccount accountOwner(InternalUserReference accountOwner) {
    
    this.accountOwner = accountOwner;
    return this;
  }

   /**
   * Get accountOwner
   * @return accountOwner
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public InternalUserReference getAccountOwner() {
    return accountOwner;
  }


  public void setAccountOwner(InternalUserReference accountOwner) {
    this.accountOwner = accountOwner;
  }


  public SFDCAccount sfdcOpportunities(List<SFDCOpportunityReference> sfdcOpportunities) {
    
    this.sfdcOpportunities = sfdcOpportunities;
    return this;
  }

  public SFDCAccount addSfdcOpportunitiesItem(SFDCOpportunityReference sfdcOpportunitiesItem) {
    if (this.sfdcOpportunities == null) {
      this.sfdcOpportunities = new ArrayList<>();
    }
    this.sfdcOpportunities.add(sfdcOpportunitiesItem);
    return this;
  }

   /**
   * Get sfdcOpportunities
   * @return sfdcOpportunities
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<SFDCOpportunityReference> getSfdcOpportunities() {
    return sfdcOpportunities;
  }


  public void setSfdcOpportunities(List<SFDCOpportunityReference> sfdcOpportunities) {
    this.sfdcOpportunities = sfdcOpportunities;
  }


  public SFDCAccount caesarReference(CaesarIdSetReference caesarReference) {
    
    this.caesarReference = caesarReference;
    return this;
  }

   /**
   * Get caesarReference
   * @return caesarReference
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public CaesarIdSetReference getCaesarReference() {
    return caesarReference;
  }


  public void setCaesarReference(CaesarIdSetReference caesarReference) {
    this.caesarReference = caesarReference;
  }


  public SFDCAccount portalInfo(List<Subscription> portalInfo) {
    
    this.portalInfo = portalInfo;
    return this;
  }

  public SFDCAccount addPortalInfoItem(Subscription portalInfoItem) {
    if (this.portalInfo == null) {
      this.portalInfo = new ArrayList<>();
    }
    this.portalInfo.add(portalInfoItem);
    return this;
  }

   /**
   * Get portalInfo
   * @return portalInfo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Subscription> getPortalInfo() {
    return portalInfo;
  }


  public void setPortalInfo(List<Subscription> portalInfo) {
    this.portalInfo = portalInfo;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SFDCAccount sfDCAccount = (SFDCAccount) o;
    return Objects.equals(this.name, sfDCAccount.name) &&
        Objects.equals(this.enterpriseId, sfDCAccount.enterpriseId) &&
        Objects.equals(this.emailDomain, sfDCAccount.emailDomain) &&
        Objects.equals(this.accountOwner, sfDCAccount.accountOwner) &&
        Objects.equals(this.sfdcOpportunities, sfDCAccount.sfdcOpportunities) &&
        Objects.equals(this.caesarReference, sfDCAccount.caesarReference) &&
        Objects.equals(this.portalInfo, sfDCAccount.portalInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, enterpriseId, emailDomain, accountOwner, sfdcOpportunities, caesarReference, portalInfo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SFDCAccount {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    enterpriseId: ").append(toIndentedString(enterpriseId)).append("\n");
    sb.append("    emailDomain: ").append(toIndentedString(emailDomain)).append("\n");
    sb.append("    accountOwner: ").append(toIndentedString(accountOwner)).append("\n");
    sb.append("    sfdcOpportunities: ").append(toIndentedString(sfdcOpportunities)).append("\n");
    sb.append("    caesarReference: ").append(toIndentedString(caesarReference)).append("\n");
    sb.append("    portalInfo: ").append(toIndentedString(portalInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

